//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestWeb.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="ServiceReference.LoginPlugin")]
    public interface LoginPlugin {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LoginPlugin/DoWork", ReplyAction="urn:LoginPlugin/DoWorkResponse")]
        string DoWork(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LoginPlugin/DoWork", ReplyAction="urn:LoginPlugin/DoWorkResponse")]
        System.Threading.Tasks.Task<string> DoWorkAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoginPluginChannel : UnitTestWeb.ServiceReference.LoginPlugin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginPluginClient : System.ServiceModel.ClientBase<UnitTestWeb.ServiceReference.LoginPlugin>, UnitTestWeb.ServiceReference.LoginPlugin {
        
        public LoginPluginClient() {
        }
        
        public LoginPluginClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginPluginClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginPluginClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginPluginClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string DoWork(string name) {
            return base.Channel.DoWork(name);
        }
        
        public System.Threading.Tasks.Task<string> DoWorkAsync(string name) {
            return base.Channel.DoWorkAsync(name);
        }
    }
}
